MindU_I2/MindU_I2/Controllers/ArtsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MindU_I2.Models;

namespace MindU_I2.Controllers
{
    public class ArtsController : Controller
    {
        private MindUEntities db = new MindUEntities();

        // GET: Arts
        public ActionResult Index()
        {
            return View(db.Arts.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MindU_I2/MindU_I2/Controllers/HomeController.cs
using MindU_I2.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MindU_I2.Controllers
{
    public class HomeController : Controller
    {
        private MindUEntities db = new MindUEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {

            return View();
        }
        public ActionResult HelpLine()
        {
            return View();
        }

        public ActionResult TestCard()
        {
            return View();
        }
 
      
        [HttpPost]
        public ActionResult Result(RSInput input)
        {
            //initialise the models and ViewBag values that would be returned to the view.
            List<Art> arts = null;
            List<Sport> sports = null;
            ViewBag.needPH = false;
            ViewBag.needInfo = false;

            if (input.likeArt == true) {
            //get a list of art ratings
            List<ArtRating> aRatings = db.ArtRatings.ToList();
            //get the top-3 aids based on the no. of likes
            var aIds = aRatings.OrderByDescending(r => int.Parse(r.likes)).Select(r => r.aid).Take(3).ToList();
            //find the top-3 art items from the arts table
            arts = db.Arts.Where(a => aIds.Contains(a.aid)).ToList();
            }
            if (input.likeSport) {

                //get a list of sport ratings
                List<SportRating> sRatings = db.SportRatings.ToList();
                //get the top-3 sids based on the no. of likes
                var sIds = sRatings.OrderByDescending(r => int.Parse(r.likes)).Select(r => r.sid).Take(3).ToList();
                //find the top-3 sport items from the arts table
                sports = db.Sports.Where(s => sIds.Contains(s.sid)).ToList();
            }
            if (input.needPH == true) {
                ViewBag.needPH = true;
            }
            if (input.needInfo == true)
            {
                ViewBag.needInfo = true;
            }
            //return a tuple containing two models back to the view
            return View(Tuple.Create(arts, sports));
        }
    }

}

MindU_I2/MindU_I2/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MindU_I2.Models;
using System.Net;
using System.IO;
using Newtonsoft.Json;

namespace MindU_I2.Controllers
{
    public class ServicesController : Controller
    {

  
        public ActionResult ConditionsInfo()
        {
            return View();
        }

        public ActionResult MentalHealthContext()
        {
            return View();
        }

        public ActionResult Tips()
        {
            return View();
        }

        public ActionResult YoungPeopleMentalHealth()
        {
            return View();
        }    
        public ActionResult Search(string category)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Please choose category", Value = "Please choose category" });
            items.Add(new SelectListItem { Text = "Psychological Consultant", Value = "Psychological Consultant" });
            items.Add(new SelectListItem { Text = "Psychological Clinic", Value = "Psychological Clinic" });
            items.Add(new SelectListItem { Text = "Psychologist", Value = "Psychologist" });
            ViewBag.defaultSelect = "Please choose category";
            ViewBag.selectList = items;
            // Display SearchResult.html page that shows results associated with selected category.
            string apiKey = "AIzaSyC-XG2JrTbessPRoSMRbasmtCwBY8oR2iI";
            var venues = new List<Venue>();
            if (category == null)
            {
                ViewBag.result = 0;
                return View(venues);

            }
            if (category.Contains(" "))
            {
                category.Replace(" ", "+");
            }
            var request = WebRequest.Create("https://maps.googleapis.com/maps/api/place/textsearch/json?query=" + category + "+in+Vic" + "&key=" + apiKey);
            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            Stream dataStream = response.GetResponseStream();
            StreamReader reader = new StreamReader(dataStream);
            string responseString = reader.ReadToEnd();
            dynamic jsonData = JsonConvert.DeserializeObject(responseString);
            //var venues = new List<Venue>();
            if (jsonData.results == null)
            {
                ViewBag.result = 1;
                return View(venues);
            }
            foreach (var item in jsonData.results)
            {
                string ratingx = item.rating;
                if (ratingx.Contains("5"))
                {
                    venues.Add(new Venue
                    {
                        name = item.name,
                        formatted_address = item.formatted_address,
                        rating = item.rating,
                        place_id = item.place_id,
                        lat = item.geometry.location.lat,
                        lng = item.geometry.location.lng
                    });
                }
            }

            foreach (var venue in venues)
            {
                request = WebRequest.Create("https://maps.googleapis.com/maps/api/place/details/json?placeid=" + venue.place_id + "&fields=formatted_phone_number,website&key=" + apiKey);
                response = (HttpWebResponse)request.GetResponse();
                dataStream = response.GetResponseStream();
                reader = new StreamReader(dataStream);
                responseString = reader.ReadToEnd();
                jsonData = JsonConvert.DeserializeObject(responseString);
                venue.formatted_phone_number = jsonData["result"]["formatted_phone_number"];
                venue.website = jsonData["result"]["website"];

            }
            return View(venues);
        }
        }
    }

MindU_I2/MindU_I2/Controllers/SportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MindU_I2.Models;

namespace MindU_I2.Controllers
{
    public class SportsController : Controller
    {
        private MindUEntities db = new MindUEntities();

        // GET: Sports
        public ActionResult Index()
        {
            return View(db.Sports.ToList());
        }

        // GET: Sports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sport sport = db.Sports.Find(id);
            if (sport == null)
            {
                return HttpNotFound();
            }
            return View(sport);
        }

        // GET: Sports/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "sid,name,address,suburb,postcode,state,category,contact")] Sport sport)
        {
            if (ModelState.IsValid)
            {
                db.Sports.Add(sport);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sport);
        }

        // GET: Sports/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sport sport = db.Sports.Find(id);
            if (sport == null)
            {
                return HttpNotFound();
            }
            return View(sport);
        }

        // POST: Sports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "sid,name,address,suburb,postcode,state,category,contact")] Sport sport)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sport);
        }

        // GET: Sports/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sport sport = db.Sports.Find(id);
            if (sport == null)
            {
                return HttpNotFound();
            }
            return View(sport);
        }

        // POST: Sports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sport sport = db.Sports.Find(id);
            db.Sports.Remove(sport);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MindU_I2/MindU_I2/Views/Home/Index.cshtml
@model MindU_I2.Models.RSInput
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
@Styles.Render("~/Content/RS_Home.css")
<script>
    $("document").ready(function () {
        $('#about_btn').click(function () {
            $('html, body').animate({
                scrollTop: $(".about").offset().top
            }, 2500);
        });
    });
    $("document").ready(function () {
        $('#service_btn').click(function () {
            $('html, body').animate({
                scrollTop: $(".services_section").offset().top
            }, 2500);
        });
    });
    $("document").ready(function () {
        $('#rs_btn').click(function () {
            $('html, body').animate({
                scrollTop: $(".recommend_system").offset().top
            }, 2500);
        });
    });
</script>
<!--banner-->
<header class="masthead text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto" style="margin-top:21%; margin-left:10%">
                <h1 class="text-uppercase" style="color:white;">
                    <strong>Your best choice to have a healthy lifestyle</strong>
                </h1>
                <a id="about_btn" class="btn btn-primary btn-xl">WHO WE ARE</a>
                <a id="service_btn" class="btn btn-primary btn-xl">FIND A SERVICE</a>
                <a id="rs_btn" class="btn btn-primary btn-xl">MORE INFO</a>
            </div>
        </div>
    </div>
</header>
<!-- Page Content -->
<!--Section About-->
<section class="about" style="background-color:#F05F40">
    <div class="container">
        <div class="row" style="margin-top:5%;  color:white;">
            <div class="col-lg-12 mx-auto text-center">
                <h1 class="section-heading text-white">WHO WE ARE</h1>
                <p style="font-size:larger">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                <p style="font-size:larger">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                <button class="btn btn-light btn-xl" style="margin-bottom:5%;">Get Started!</button>
            </div>
        </div>
    </div>
</section>
<!--Section Services-->
<section class="services_section" id="services">
    <div class="row">
        <div class="col-lg-3 col-md-6 services-item">
            <div class="b_card-text">
                <a href='@Url.Action("Index", "Arts")'>
                    <img src="@Url.Content("~/Images/boxes/ph_test.png")" alt="conditions">
                </a>
                <h1 class="b_card-title">
                    Professinal Help
                </h1>
                <div class="b_card-body">
                    <p class="b_card-text">
                        need some desciption here
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 services-item">
            <div class="b_card-text">
                <a href='@Url.Action("Index", "Arts")'>
                    <img src="@Url.Content("~/Images/boxes/ph_test.png")" alt="conditions">
                </a>
                <h1 class="b_card-title">
                    Art Spaces
                </h1>
                <div class="b_card-body">
                    <p class="b_card-text">
                        need some desciption here
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 services-item">
            <div class="b_card-text">
                <a href='@Url.Action("Index", "Arts")'>
                    <img src="@Url.Content("~/Images/boxes/ph_test.png")" alt="conditions">
                </a>
                <h1 class="b_card-title">
                    Sports Acvities
                </h1>
                <div class="b_card-body">
                    <p class="b_card-text">
                        need some desciption here
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 services-item">
            <div class="b_card-text">
                <a href='@Url.Action("Index", "Arts")'>
                    <img src="@Url.Content("~/Images/boxes/ph_test.png")" alt="conditions">
                </a>
                <h1 class="b_card-title">
                    Hotlines
                </h1>
                <div class="b_card-body">
                    <p class="b_card-text">
                        need some desciption here
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--.Section Leisure-->
<!--Section RS-->
<!--Section RS-->
@*<div class="col-lg-12" style="background-color:#F7F1E5;">*@
<!--Section RS-->
@*<div class="col-lg-12" style="background-color:#F7F1E5;">*@
@*
    <section class="recommend_system" style="background-color:#F05F40">
        <h2 class="text-center">For more info, tell me what you like...</h2>
        <div style="margin-left:15%; background-color:wheat;">
            @using (Html.BeginForm("Result", "Home", FormMethod.Post))
            {

                <div class="form-group">
                    <div class="col-lg-12">
                        <h3>Are you intereted in arts: </h3>
                    </div>
                    <div class="col-md-1  text-center">
                        @Html.RadioButton("likeArt", true, false, new { @id = "radio-img-1" })
                        @Html.Label("radio-img-1", new { @class = "Yes" })
                    </div>
                    <div class="col-md-1  text-center">
                        @Html.RadioButton("likeArt", false, false, new { @id = "radio-img-2" })
                        @Html.Label("radio-img-2", new { @class = "No" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-12">
                        <h3>Are you intereted in sports:</h3>
                    </div>
                    <div class="col-md-1  text-center">
                        @Html.RadioButton("likeSport", true, false, new { @id = "radio-img-3" })
                        @Html.Label("radio-img-3", new { @class = "Yes" })
                    </div>
                    <div class="col-md-1  text-center">
                        @Html.RadioButton("likeSport", false, false, new { @id = "radio-img-4" })
                        @Html.Label("radio-img-4", new { @class = "No" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-12">
                        <h3>Would you like to talk to professinal experts? </h3>
                    </div>
                    <div class="col-md-1  text-center">
                        @Html.RadioButton("needPH", true, false, new { @id = "radio-img-5" })
                        @Html.Label("radio-img-5", new { @class = "Yes" })
                    </div>
                    <div class="col-md-1  text-center">
                        @Html.RadioButton("needPH", false, false, new { @id = "radio-img-6" })
                        @Html.Label("radio-img-6", new { @class = "No" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-12">
                        <h3>Would you like to know more about mental health conditions? </h3>
                    </div>
                    <div class="col-md-1 text-center">
                        @Html.RadioButton("needInfo", true, false, new { @id = "radio-img-7" })
                        @Html.Label("radio-img-7", new { @class = "Yes" })
                    </div>
                    <div class="col-md-1  text-center">
                        @Html.RadioButton("needInfo", false, false, new { @id = "radio-img-8" })
                        @Html.Label("radio-img-8", new { @class = "No" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-1  text-center">
                        <button type="submit" class="btn btn-light btn-xl">Submit</button>
                    </div>
                </div>
            }
        </div>
    </section>*@
@*</div>*@
<!--End Section RS-->
<section class="recommend_system" style="background-color:#F05F40; height:700px; width:100%;">
    <br />
    <h2 class="text-center" style="color:#fff">For more info, tell me what you like...</h2>
    <div class="container" style="background-color:honeydew; height:550px; width:620px; margin-top:1.8%; box-shadow:0 4px 8px 0 rgba(255, 255, 255, 0.2), 0 6px 20px 0 rgba(255, 255, 255, 0.19);">
        @using (Html.BeginForm("Result", "Home", FormMethod.Post))
        {
            <div class="form-group">
                <div class="col-lg-12">
                    <h3>Are you interested in arts? </h3>
                </div>
                <div class="col-md-12  text-center">
                    <div class="col-md-3">
                        @Html.RadioButton("likeArt", true, false, new { @id = "radio-img-1" })
                        @Html.Label("radio-img-1", new { @class = "Yes" })
                    </div>
                    <div class="col-md-4  text-center">
                        @Html.RadioButton("likeArt", false, false, new { @id = "radio-img-2" })
                        @Html.Label("radio-img-2", new { @class = "No" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-12">
                    <h3>Are you interested in sports?</h3>
                </div>
                <div class="col-md-12  text-center">
                    <div class="col-md-3  text-center">
                        @Html.RadioButton("likeSport", true, false, new { @id = "radio-img-3" })
                        @Html.Label("radio-img-3", new { @class = "Yes" })
                    </div>
                    <div class="col-md-4  text-center">
                        @Html.RadioButton("likeSport", false, false, new { @id = "radio-img-4" })
                        @Html.Label("radio-img-4", new { @class = "No" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-12">
                    <h3>Are you interested in professinal experts? </h3>
                </div>
                <div class="col-md-12  text-center">
                    <div class="col-md-3  text-center">
                        @Html.RadioButton("needPH", true, false, new { @id = "radio-img-5" })
                        @Html.Label("radio-img-5", new { @class = "Yes" })
                    </div>
                    <div class="col-md-4  text-center">
                        @Html.RadioButton("needPH", false, false, new { @id = "radio-img-6" })
                        @Html.Label("radio-img-6", new { @class = "No" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-12">
                    <h3>Are you interested in mental health conditions? </h3>
                </div>
                <div class="col-md-12  text-center">
                    <div class="col-md-3 text-center">
                        @Html.RadioButton("needInfo", true, false, new { @id = "radio-img-7" })
                        @Html.Label("radio-img-7", new { @class = "Yes" })
                    </div>
                    <div class="col-md-4  text-center">
                        @Html.RadioButton("needInfo", false, false, new { @id = "radio-img-8" })
                        @Html.Label("radio-img-8", new { @class = "No" })
                    </div>
                </div>
            </div>
            
            <div class="form-group">
                    <div class="col-md-12">
                        <br/>
                        <button type="submit" class="btn btn-primary btn-xl" style="margin-left:80%;">Submit</button>
                    </div>
            </div>
        }
    </div>
</section>

MindU_I2/MindU_I2/Views/Home/Result.cshtml
@model Tuple<List<MindU_I2.Models.Art>, List<MindU_I2.Models.Sport>>
@{
                ViewBag.Title = "Result";
                Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="img-responsive">
        <img style="width:100%;" src="@Url.Content("~/Images/banners/banner2.jpg")">
    </div>
    <div>
        <ol class="breadcrumb" style="background-color:transparent;">
            <li class="breadcrumb-item">
                <a href="@Url.Action("index", "Home")">
                    <img class="active" src="@Url.Content("~/Images/home_icon2.png")">
                </a>
            </li>
            <li class="breadcrumb-item active">Recommendations</li>
        </ol>
    </div>
    <!--Art Results-->
    @if (Model.Item1 != null)
    {
        <section class="art_results">
            @foreach (var item in Model.Item1)
            {
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="card" style="width:360px; height:450px;">
                        <p class="card-head">
                            @foreach (var imgItem in item.ArtImages)
                            {
                                <a href=@item.website )>
                                    <img src="@Url.Content("~/images/arts/" + Path.GetFileName(imgItem.imgPath))" alt=@item.name ) width="360" height="200" />
                                </a>
                            }
                        </p>
                        <h3 class="card-title">
                            @item.name
                        </h3>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="@Url.Content("~/Images/info_icons/map_icon.png")">
                                :
                                @item.address,  @item.suburb),  @item.state,  @item.postcode
                            </p>
                        </div>
                        <div class="text-center">
                            <p class="card-text">
                                <a href="@Url.Action("Index", "Arts")" style="position:absolute; top:88%; left:60%; ">More @item.website</a>
                            </p>
                        </div>

                    </div>
                </div>
            }
        </section>
    }
    @if (Model.Item2 != null)
    {
        <!--Sport Result-->
        <section class="sport_result">
            @foreach (var item in Model.Item2)
            {
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="card" style="width:360px; height:450px;">
                        <p class="card-head">
                            @foreach (var imgItem in item.SportImages)
                            {
                                <img src="@Url.Content("~/images/sports/sport" + Path.GetFileName(imgItem.imgPath))" alt=@item.name ) width="360" height="200" />

                            }
                        </p>
                        <h3 class="card-title">
                            @item.name
                        </h3>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="@Url.Content("~/Images/info_icons/map_icon.png")">
                                :
                                @item.address,  @item.suburb,  @item.state,  @item.postcode
                            </p>
                            <p class="card-text">
                                <img src="@Url.Content("~/Images/info_icons/phone_icon.png")">
                                : @item.contact
                            </p>
                        </div>
                        <div>
                            <p class="card-text">
                                <a href="@Url.Action("Index", "Sports")" style="position:absolute; top:88%; left:45%; ">More @item.category</a>
                            </p>
                        </div>
                    </div>
                </div>

            }
        </section>
    }
    <!--Professional Help Section-->
    @if (ViewBag.needPH == true)
    {
        <section class="PH_results">
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card" style="width:360px; height:450px;">
                    <p class="card-head">
                        <img src="@Url.Content("~/images/rs_cards/ph_card.jpg")" alt=professinal_help) width="360" height="200" />
                    </p>
                    <h3 class="card-title">
                        Professional Help
                    </h3>
                    <div class="card-body">
                        <p class="card-text">
                            need some desciption here
                        </p>
                    </div>
                    <div class="text-center">
                        <p class="card-text">
                            <a href="@Url.Action("Search", "Services", new { category = "Psychological Clinic"})" style="position:absolute; top:88%; left:70%; ">More Info</a>
                        </p>
                    </div>

                </div>
            </div>
        </section>
    }
    <!--Mental Health Condition Part-->
    @if (ViewBag.needInfo == true)
    {
        <section class="MH_results">
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card" style="width:360px; height:450px;">
                    <p class="card-head">
                        <img src="@Url.Content("~/images/rs_cards/mh_card.jpg")" alt=mental_health width="360" height="200" />
                    </p>
                    <h3 class="card-title">
                        Mental Health Conditions
                    </h3>
                    <div class="card-body">
                        <p class="card-text">
                            need some desciption here
                        </p>
                    </div>
                    <div class="text-center">
                        <p class="card-text">
                            <a href="@Url.Action("ConditionsInfo", "Services")" style="position:absolute; top:88%; left:75%; ">More Info</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card" style="width:360px; height:450px;">
                    <p class="card-head">
                        <img src="@Url.Content("~/images/people/people1.jpg")" alt=article1 width="360" height="200" />
                    </p>

                    <h3 class="card-title">
                        Panic Attack
                    </h3>
                    <div class="card-body">
                        <p class="card-text">
                            A panic attack is a brief episode of intense anxiety, which causes the physical sensations of fear. 
                        </p>
                    </div>
                    <div class="text-center">
                        <p class="card-text">
                            <a href="@Url.Action("Articles", "Services")" style="position:absolute;  top:88%; left:75%; ">More Info</a>
                        </p>
                    </div>

                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card" style="width:360px; height:450px;">
                    <p class="card-head">
                        <img src="@Url.Content("~/images/rs_cards/mh_card.jpg")" alt=mental_health_conditions) width="360" height="200" />
                    </p>
                    <h3 class="card-title">
                        Anxiety
                    </h3>
                    <div class="card-body">
                        <p class="card-text">
                            Anxiety is more than just feeling stressed or worried. 
                    </div>
                    <div class="text-center">
                        <p class="card-text">
                            <a href="@Url.Action("Articles", "Services")" style="position:absolute; top:88%; left:75%; ">More Info</a>
                        </p>
                    </div>
                </div>
            </div>
         </section>
    }
    </div>